<div class="post nunito">
    <h3 class="titrePost merienda">Lorem ipsum dolor sit amet consectetur</h3>
        <div class="categoryPost">(Saisons)</div>
            <div class="poster">
               <img src="./images/ours.png" alt="profile picture" class="profile-picture-poster"> Jean Valjean, dév indépendant, 17 ans de métier</div>
                <div class="content">
Lorem ipsum dolor sit amet consectetur adipisicing elit. Omnis, adipisci harum animi error hic sapiente dolores reiciendis
                    ipsum fugiat aspernatur quaerat aut accusamus, est dignissimos! Magnam autem inventore odit consequatur!
Impedit culpa error similique expedita veniam facere consectetur, facilis fugiat at? Quidem aliquid,
                    voluptas
                    </div>
                <div class="date nunito">Posté le 14/06/18 à 22:14</div>

                <div class="answers">
                    <div class="answers-eval">Réponses pertinentes : 17</div>
                    <div class="react">
                            <span>
                                <p class="blue cursor show" id="Bouton">Répondre</p>
                            </span>
                        <span>
                                <p class="cursor blue answer" href="#" >Voir</p>
                            </span>
                    </div>
                </div>
                <div id="giveAnswer">
                    <form action="comment.php" method="POST">
                        <textarea onkeyup="auto_grow(this)" id="write" class="writeAnswer nunito" placeholder="Je partage mon expérience, fais appel à la communauté..."></textarea>
                        <button type="submit" class="validComment nunito color-blank">Je valide</button>
                    </form>
                </div>
            </div>