<body>
<!-- Deux div pour centrer verticalement la popin sur la page -->
<div class="table-popin">
    <div class="center-popin">

        <header>
            <nav class="headerElements color-blank nunito text-color center-text">
                <ul>
                    <a href="#" class="simeliusName merienda color-blank">
                        <img class="logoSimelius" src="http://www.efrei.fr/wp-content/uploads/2015/07/logo-Entraide.png" alt="Logo Simelius">Simelius</a>
                    <li>
                        <input type="text" class="searchBar" placeholder="Rechercher">
                    </li>
                    <li>
                        <div class="user">
                            <p class="username">Lion rouge</p>
                            <img src="Profil.png" alt="profile-picture" class="profile-picture">
                        </div>
                    </li>
                </ul>
            </nav>
        </header>

        <div class="sidenavleft sidenav nunito">
            <div class="sideBarContent">
                <a href="#about" class="color-blank" class="category">Catégories</a>
            </div>
            <div class="sideBarContent">
                <a href="#services" class="color-blank" class="category">CAT1</a>
            </div>
            <div class="sideBarContent">
                <a href="#clients" class="color-blank" class="category">CAT2</a>
            </div>
            <div class="sideBarContent">
                <a href="#contact" class="color-blank" class="category">CAT3</a>
            </div>
            <div class="sideBarContent">
                <a href="#contact" class="color-blank" class="category">CAT4</a>
            </div>
            <div class="sideBarContent">
                <a href="#contact" class="color-blank" class="category">CAT5</a>
            </div>
            <div class="sideBarContent">
                <a href="#contact" class="color-blank" class="category">CAT6</a>
            </div>
            <div class="sideBarContent">
                <a href="#contact" class="color-blank" class="category">CAT7</a>
            </div>
            <div class="sideBarContent">
                <a href="#contact">Voir plus</a>
            </div>
        </div>

        <div class="sidenavright sidenav nunito">
            <div class="sideBarContent">
                <a href="#about" class="color-blank" class="event">Suicide digestif</a>
            </div>
            <div class="sideBarContent">
                <a href="#services" class="color-blank" class="event">Spiritisme collectif</a>
            </div>
            <div class="sideBarContent">
                <a href="#clients" class="color-blank" class="event">Sylvanothérapie</a>
            </div>
            <div class="sideBarContent">
                <a href="#contact" class="color-blank" class="event">Miaou</a>
            </div>
        </div>

        <div class="container">
            <h2 class="merienda center-text" style="padding-bottom: 50px">Evenement</h2>
            <h3 class="merienda center-text" style="padding-bottom: 50px">Sujet : Lorem ipsum dolor sit amet consectetur adipisicing elit. Iusto, corporis.</h3>


            <div class="spec">
                <div class="bloc1">
                    <div class="theme">
                        <h2>Thématiques abordées</h2>
                        <ul>
                            <li><i class="fas fa-star"></i> Item1</li>
                            <li><i class="fas fa-heart"></i> Item2</li>
                            <li><i class="fas fa-user-alt"></i> Item3</li>
                        </ul>
                    </div>

                    <div class="speaker">
                        <h2>Intervenants</h2>
                        <ul>
                            <li><i class="fas fa-star"></i> Item1</li>
                            <li><i class="fas fa-heart"></i> Item2</li>
                            <li><i class="fas fa-user-alt"></i> Item3</li>
                        </ul>
                    </div>
                </div>

                <div class="bloc2">
                    <p>Description<br> ipsum dolor sit amet consectetur, adipisicing elit. Modi ut quis adipisci nihil aperiam, quia illum? Incidunt doloremque, fugiat necessitatibus eaque perspiciatis fuga provident autem explicabo fugit, quam officiis corporis!mLorem ipsum dolor sit amet consectetur, adipisicing elit. Modi ut quis adipisci nihil aperiam, quia illum? Incidunt doloremque, fugiat necessitatibus eaque perspiciatis fuga provident autem explicabo fugit, quam officiis corporis!m</p>
                </div>

                <div class="bloc3">
                    <div class="map">
                        <img src="img/lille.gif" alt="plan lille">
                    </div>
                    <div class="info">
                        <h4>Infos Pratiques</h4><br>
                        Date
                        <p>Lorem, ipsum dolor sit amet consectetur adipisicing elit. Laborum debitis similique nulla voluptates eaque magnam adipisci dolorum vel laboriosam recusandae aut, sequi quas ipsam sed possimus velit molestiae at omnis.</p>



                    </div>

                </div>
                <button class="btn">Je participe</button>
            </div>
        </div>
    </div>
</div>
</body>

</html>