<?php if (!isset($_SESSION['user'])) {
    header('Location: login.php');
} else ?>
<!-- Deux div pour centrer verticalement la popin sur la page -->
<div class="table-popin">
    <div class="center-popin">

        <header>
            <nav class="headerElements color-blank nunito text-color center-text">
                <ul>
                    <a href="#" class="simeliusName merienda color-blank">
                        <img class="logoSimelius" src="http://www.efrei.fr/wp-content/uploads/2015/07/logo-Entraide.png" alt="Logo Simelius">Simelius</a>
                    <li>
                        <input type="text" class="searchBar" placeholder="Rechercher">
                    </li>
                    <li>
                        <div class="user">
                            <p class="username">Lion rouge</p>
                            <img src="./images/Profil.png" alt="profile-picture" class="profile-picture">
                        </div>
                    </li>
                </ul>
            </nav>
        </header>

        <div class="sidenavleft sidenav nunito">
            <?php foreach ($category as $cat) : ?>
                <div class="sideBarContent">
                    <a href="#about" class="color-blank" class="category"><?= $cat['name']; ?></a>
                </div>
            <?php endforeach;?>
        </div>

        <div class="sidenavright sidenav nunito">
            <div class="sideBarContent">
                <a href="#about" class="color-blank" class="event">Suicide digestif</a>
            </div>
            <div class="sideBarContent">
                <a href="#services" class="color-blank" class="event">Spiritisme collectif</a>
            </div>
            <div class="sideBarContent">
                <a href="#clients" class="color-blank" class="event">Sylvanothérapie</a>
            </div>
            <div class="sideBarContent">
                <a href="#contact" class="color-blank" class="event">Miaou</a>
            </div>
        </div>
        <div class="main">
            <h3 class="page-title merienda center-text">Nous sommes</h3>
            <h2 class="merienda center-text"><?= $user['name'] ?>s</h2>
            <form method="post" class="addPost">
                <div class="newPost">

                <textarea onkeyup="auto_grow(this)" name="content" class="write nunito" placeholder="Je partage mon expérience, fais appel à la communauté..."></textarea>
                <a href="#popin1">
                    <div class="postButton nunito color-blank">Contribuer</div>
                </a>
                </div>
                <div class="smart-popin" id="popin1">
                <div class="sp-table">
                    <div class="sp-cell">
                        <div class="sp-body nunito">
                            <a href="#" class="sp-close">×</a>
                            <input type="text" name="title" placeholder="Mon titre" class="form-control postTitle nunito">
                            <p class="addCategories">On pourra retrouver ma contribution dans les catégories...</p>
                                <?php foreach ($category as $cat) : ?>
                                    <div>
                                        <input name="category[]" type="checkbox" value="<?= $cat['category_id']; ?>"  id="c1" />
                                        <label for="c1"><?= $cat['name']; ?></label>
                                    </div>
                                <?php endforeach;?>
                                <button type="submit" class="validButton nunito color-blank">Je valide</button>
                        </div>

                    </div>
                </div>
                </form>
            </div>
            <?php foreach ($articles as $article) : ?>
            <?php $experience= experience($article['experience'])?>
            <div class="post nunito">
                <h3 class="titrePost merienda"><?= $article['title'] ?></h3><br>
                    <div class="categoryPost">
                        <?php if(isset($article['categories'])) : ?>
                            <?php $categories = explode(',', $article['categories']); ?>
                            <?php foreach ($categories as $category) : ?>
                                <span class="badge badge-pill badge-secondary"><?= $category ?></span>
                            <?php endforeach ;?>
                        <?php endif; ?>
                    </div>
                <div class="poster">
                    <img src="" alt="image" /> <?= $article['firstname'] . ' '. $article['lastname']?>,
                     <?php if ($experience[0]<1) : ?>
                    <?= $experience[1]?> jours d'expérience
                    <?php elseif ($experience[0]=1) : ?>
                    <?= $experience[0]?> an et <?= $experience[1]?> jours d'expérience
                    <?php else : ?>
                    <?= $experience[0]?> ans et <?= $experience[1]?> jours d'expérience
                    <?php endif; ?>
                </div>
                <div class="content">
                    <?= $article['content'] ?><br>
                </div>
                <div class="date nunito">Posté le <?= (new DateTime($article['created_at']))->format('d/m/Y à H:i'); ?></div>

                    <form action="<?= BASE_URL . DS . 'comment.php' ?>" method="POST">
                        <input name="content" onkeyup="auto_grow(this)" id="write" class="writeAnswer nunito form-control" placeholder="Mon commentaire..."></input>
                        <input type="hidden" name="article_id" value="<?= $article['article_id'] ?>">
                    </form>
                <div class="answers">
                    <span class="showAnswers">
                         Afficher les réponses <i class="fas fa-chart-line"></i> 17
                    </span>
                </div>
            </div>
            <?php endforeach ;?>

        </div>
    </div>
</body>

<script type="text/javascript">
    function auto_grow(element) {
        element.style.height = "5px";
        element.style.height = (element.scrollHeight)+"px";
    };
    <?php foreach ($articles as $article) : ?>
    document.querySelector("#Bouton").onclick = function() {
        document.querySelector("#giveAnswer").style.display=(window.getComputedStyle(document.querySelector('#giveAnswer')).display=='none') ? "block" : "none";
    };
    document.querySelector("#comments").onclick = function() {
        document.querySelector("#comment").style.display=(window.getComputedStyle(document.querySelector('#comment')).display=='none') ? "block" : "none";
    }
    <?php endforeach; ?>

    var nbMaxChk = 3;
    var compteChk = 0;
    function cocher(objet) {
        if (objet.checked) {
            if (compteChk == nbMaxChk)
                objet.checked = false;
            else
                compteChk++;
        }
        else
            compteChk--;
    }
</script>

</html>