<!-- Deux div pour centrer verticalement la popin sur la page -->
<div class="table-popin">
    <div class="center-popin">

        <header>
            <nav class="headerElements color-blank nunito text-color center-text">
                <ul>
                    <a href="#" class="simeliusName merienda color-blank">
                        <img class="logoSimelius" src="http://www.efrei.fr/wp-content/uploads/2015/07/logo-Entraide.png" alt="Logo Simelius">Simelius</a>
                    <li>
                        <input type="text" class="searchBar" placeholder="Rechercher">
                    </li>
                    <li>
                        <div class="user">
                            <p class="username">Lion rouge</p>
                            <img src="./images/Profil.png" alt="profile-picture" class="profile-picture">
                        </div>
                    </li>
                </ul>
            </nav>
        </header>

        <div class="sidenavleft sidenav nunito">
            <div class="sideBarContent">
                <a href="#about" class="color-blank" class="category">Catégories</a>
            </div>
            <div class="sideBarContent">
                <a href="#services" class="color-blank" class="category">CAT1</a>
            </div>
            <div class="sideBarContent">
                <a href="#clients" class="color-blank" class="category">CAT2</a>
            </div>
            <div class="sideBarContent">
                <a href="#contact" class="color-blank" class="category">CAT3</a>
            </div>
            <div class="sideBarContent">
                <a href="#contact" class="color-blank" class="category">CAT4</a>
            </div>
            <div class="sideBarContent">
                <a href="#contact" class="color-blank" class="category">CAT5</a>
            </div>
            <div class="sideBarContent">
                <a href="#contact" class="color-blank" class="category">CAT6</a>
            </div>
            <div class="sideBarContent">
                <a href="#contact" class="color-blank" class="category">CAT7</a>
            </div>
            <div class="sideBarContent">
                <a href="#contact" class="blue">Voir plus</a>
            </div>
        </div>

        <div class="sidenavright sidenav nunito">
            <div class="sideBarContent">
                <a href="#about" class="color-blank" class="event">Suicide digestif</a>
            </div>
            <div class="sideBarContent">
                <a href="#services" class="color-blank" class="event">Spiritisme collectif</a>
            </div>
            <div class="sideBarContent">
                <a href="#clients" class="color-blank" class="event">Sylvanothérapie</a>
            </div>
            <div class="sideBarContent">
                <a href="#contact" class="color-blank" class="event">Miaou</a>
            </div>
        </div>

        <div class="main">
            <h3 class="page-title merienda center-text">Nous sommes</h3>
            <h2 class="merienda center-text">Développeurs</h2>
            <div class="newPost">
                <textarea onkeyup="auto_grow(this)" name="write" id="write" class="write nunito" placeholder="Je partage mon expérience, fais appel à la communauté..."></textarea>
                <a href="#popin1">
                    <button class="postButton nunito color-blank">Contribuer</button>
                </a>
            </div>
            <div class="smart-popin" id="popin1">
                <div class="sp-table">
                    <div class="sp-cell">
                        <div class="sp-body nunito">
                            <a href="#" class="sp-close">×</a>
                            <input type="text" name="title" placeholder="Mon titre" class="postTitle nunito">
                            <p>On pourra retrouver ma contribution dans les catégories...</p>

                            <div>
                                <input type="checkbox" onclick="cocher(this)" id="c1" />
                                <label for="c1">Catégorie 1</label>
                            </div>

                            <div>
                                <input type="checkbox" onclick="cocher(this)" id="c2" />
                                <label for="c2">Catégorie 2</label>
                            </div>
                            <div>
                                <input type="checkbox" onclick="cocher(this)" id="c3" />
                                <label for="c3">Catégorie 3</label>
                            </div>
                            <div>
                                <input type="checkbox" onclick="cocher(this)" id="c4" />
                                <label for="c4">Catégorie 4</label>
                            </div>
                            <div>
                                <input type="checkbox" onclick="cocher(this)" id="c5" />
                                <label for="c5">Catégorie 5</label>
                            </div>
                            <div>
                                <input type="checkbox" onclick="cocher(this)" id="c6" />
                                <label for="c6">Catégorie 6</label>
                            </div>
                            <div>
                                <input type="checkbox" onclick="cocher(this)" id="c7" />
                                <label for="c7">Catégorie 7</label>
                            </div>

                            <button class="validButton nunito color-blank">Je valide</button>
                        </div>

                    </div>
                </div>

            </div>
            <div class="post nunito">
                <h3 class="titrePost merienda">Lorem ipsum dolor sit amet consectetur
                </h3>
                <div class="categoryPost">(Saisons)</div>
                <div class="poster">
                    <img src="./images/ours.png" alt="profile picture" class="profile-picture-poster"> Jean Valjean, dév indépendant, 17 ans de métier</div>
                <div class="content">
                    Lorem ipsum dolor sit amet consectetur adipisicing elit. Omnis, adipisci harum animi error hic sapiente dolores reiciendis
                    ipsum fugiat aspernatur quaerat aut accusamus, est dignissimos! Magnam autem inventore odit consequatur!
                    Impedit culpa error similique expedita veniam facere consectetur, facilis fugiat at? Quidem aliquid,
                    voluptas
                </div>
                <div class="date nunito">Posté le 14/06/18 à 22:14</div>

                <div class="answers">
                    <div class="answers-eval">Réponses pertinentes : 17</div>
                    <div class="react">
                            <span>
                                <p class="blue cursor show" id="Bouton">Répondre</p>
                            </span>
                        <span>
                                <p class="cursor blue answer" href="#" >Voir</p>
                            </span>
                    </div>
                </div>
                <div id="giveAnswer">
                    <form action="comment.php" method="POST">
                        <textarea onkeyup="auto_grow(this)" id="write" class="writeAnswer nunito" placeholder="Je partage mon expérience, fais appel à la communauté..."></textarea>
                        <button type="submit" class="validComment nunito color-blank">Je valide</button>
                    </form>
                </div>
            </div>
            <div class="post nunito">
                <h3 class="titrePost merienda">Lorem ipsum dolor sit amet consectetur.</h3>
                <div class="categoryPost">(Dodo)</div>
                <div class="poster">
                    <img src="./images/Pikachu.png" alt="profile picture" class="profile-picture-poster">Sade Marquis, dév expérimenté, 250 ans de métier</div>
                <div class="content">
                    Lorem ipsum dolor sit amet consectetur adipisicing elit. Omnis, adipisci harum animi error hic sapiente dolores reiciendis
                    ipsum fugiat aspernatur quaerat aut accusamus, est dignissimos! Magnam autem inventore odit consequatur!
                    Impedit culpa error similique expedita veniam facere consectetur, facilis fugiat at? Quidem aliquid,
                    voluptas dolor sapiente ducimus beatae numquam quae quia! Tempore harum tenetur dolor? Iure incidunt
                    id quidem voluptate? Laborum deleniti odit, sit cum blanditiis sint sed laudantium tenetur ut provident
                    repellendus alias ipsam, officia asperiores quidem ullam adipisci. Nihil est, itaque esse id et possimus.
                    Adipisci, autem. Deserunt. Facere consequuntur asperiores voluptates voluptate perferendis animi
                    earum sapiente dolorem, reprehenderit facilis commodi rerum ab sit iste molestiae ea illum cumque
                    consectetur amet eaque minima? Nihil illo dolorem sit hic?
                </div>
                <div class="date nunito">Posté le 22/24/26 à 22:14</div>

                <div class="answers">
                    <div class="answers-eval">Réponses pertinentes : 17</div>
                    <div class="react">
                                <span>
                                    <p class="blue cursor show" id="Bouton">Répondre</p>
                                </span>
                        <span>
                                    <p class="cursor blue answer" id="comments">Voir</p>
                                </span>
                    </div>
                </div>
                <div id="giveAnswer">
                    <form action="comment.php" method="POST">
                        <textarea onkeyup="auto_grow(this)" id="write" class="writeAnswer nunito" placeholder="Je partage mon expérience, fais appel à la communauté..."></textarea>
                        <button type="submit" class="validComment nunito color-blank">Je valide</button>
                    </form>
                </div>
            </div>
            <div class="comment">
                <div class="poster nunito">
                    <img src="Pikachu.png" alt="profile picture" class="profile-picture-poster">Sade Marquis, dév expérimenté, 250 ans de métier</div>
                <div class="content nunito">
                    Lorem ipsum, dolor sit amet consectetur adipisicing elit. Suscipit inventore beatae aliquid, neque officia dolores deserunt. Minima officiis veniam eveniet.
                </div>
                <div class="date nunito">Posté le 22/24/26 à 22:14</div>
                <div class="pertinence nunito">Pertinence de la réponse : 7</div>
                <div class="blue cursor like">++</div>
            </div>
        </div>
    </div>
</div>
</body>

<script type="text/javascript">
    function auto_grow(element) {
        element.style.height = "5px";
        element.style.height = (element.scrollHeight)+"px";
    };
    document.querySelector("#Bouton").onclick = function() {
        document.querySelector("#giveAnswer").style.display=(window.getComputedStyle(document.querySelector('#giveAnswer')).display=='none') ? "block" : "none";
    };
    document.querySelector("#comments").onclick = function() {
        document.querySelector("#comment").style.display=(window.getComputedStyle(document.querySelector('#comment')).display=='none') ? "block" : "none";
    }

    var nbMaxChk = 3;
    var compteChk = 0;
    function cocher(objet) {
        if (objet.checked) {
            if (compteChk == nbMaxChk)
                objet.checked = false;
            else
                compteChk++;
        }
        else
            compteChk--;
    }
</script>

</html>