    <header>
        <nav class="navbar navbar-light">
            <a class="navbar-brand" href="<?=BASE_URL?>/homepage.php">
                <img class="logoSimelius" src="http://www.efrei.fr/wp-content/uploads/2015/07/logo-Entraide.png" alt="Logo Simelius"><span class="simeliusName merienda">Simelius</span>
            </a>
            <?php if (!empty($errors)) : ?>
                <?php foreach ($errors as $err) : ?>
                    <span class="mb-0 errLog alert alert-danger"><?= $err; ?></span>
                <?php endforeach; ?>
            <?php endif; ?>
            <form class="mb-0 form-inline form-group loginForm" method="post" action="<?= BASE_URL . DS . 'login.php'?>">
                <input class="form-control inputLog mr-2 email" type="email" name="email" id="email" placeholder="Adresse mail">
                <input class="form-control inputLog mr-2" type="password" name="password" id="password" placeholder="Mot de passe">
                <button type="submit" class="button connexionButton">Connexion</button>
            </form>
        </nav>
    </header>

    <div class="title">
    <h1 class="Simelius">Simelius</h1>
    <h2>Ensemble, soyons meilleur</h2>
    </div>
    <a href="#popin1">
        <button class="button inscriptionButton">Rejoindre la communauté</button>
    </a>

    <div class="smart-popin" id="popin1">
        <div class="sp-table">
            <div class="sp-cell">
                <div class="sp-body">
                    <a href="#" class="sp-close">×</a>
                    <div class="centre">
                        <form method="POST" action="<?=BASE_URL . DS . 'register.php' ?>" class="registerForm" enctype="multipart/form-data">
                            <?php if (!empty($errors)) : ?>
                                <?php foreach ($errors as $err) : ?>
                                    <div class="alert alert-danger"><?= $err; ?></div>
                                <?php endforeach; ?>
                            <?php endif; ?>
                            <div class="form-group">
                            <input class="form-control inputRegister" type="text" name="lastname" id="lastname" placeholder="Nom">
                            <input class="form-control inputRegister" type="text" name="firstname" id="firstname" placeholder="Prénom">
                            <select class="form-control inputRegister" name="profession_id">
                                <?php foreach ($professionfromdb as $prof) :?>
                                    <option value="<?= $prof['profession_id']?>"><?= $prof['name']?></option>
                                <?php endforeach ?>
                            </select>
                                <label for="email" class="sr-only">Email</label>
                                <input class="form-control inputRegister" type="email" name="email" id="registerMail" placeholder="Adresse mail" value="<?= $email; ?>" required autofocus>
                                <div id="hasUser" class="invalid-feedback form-text">Cette adresse mail est déjà utilisée.
                                </div>
                            <input class="form-control inputRegister" type="password" name="password" id="password" placeholder="Mot de passe">
                            <input class="form-control inputRegister" type="password" name="password2" id="password2" placeholder="Vérification du mot de passe">
                            <input class="form-control inputRegister" placeholder="J'ai commencé à exercer..." type="text" onfocus="(this.type='date')" onblur="(this.type='text')" name="birthday" id="date">
                                <input class="form-control inputRegister" type="file" id="monfichier" name="profile_picture" >

                                <button class="submitButton nunito color-blank"> Je rejoins la communauté</button>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>


    <footer>
        <p class="text-color">Partagez la vôtre et bénéficiez de l'expérience de vos pairs pour acquérir de nouvelles compétences et progresser
            professionnellement.
        </p>
    </footer>

</div>
</body>
    <script src="<?= BASE_URL ?>/views/<?= THEME ?>/js/register.js"></script>
</html>