<!DOCTYPE html>
<html lang="fr">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link href="https://fonts.googleapis.com/css?family=Merienda+One|Nanum+Gothic" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Nunito" rel="stylesheet">
    <link rel="stylesheet" href="<?= CSS_PATH . DS . 'login.css' ?>">
</head>

<body>
    <header>
        <nav class="navbar navbar-light">
            <a class="navbar-brand" href="<?=BASE_URL?>/homepage.php">
                <img class="logoSimelius" src="http://www.efrei.fr/wp-content/uploads/2015/07/logo-Entraide.png" alt="Logo Simelius"><span class="simeliusName merienda">Simelius</span>
            </a>
            <?php if (!empty($errors)) : ?>
                <?php foreach ($errors as $err) : ?>
                    <span class="mb-0 errLog alert alert-danger"><?= $err; ?></span>
                <?php endforeach; ?>
            <?php endif; ?>
            <form class="mb-0 form-inline form-group loginForm" method="post" action="<?= BASE_URL . DS . 'login.php'?>">
                <input class="form-control inputLog mr-2" type="mail" name="email" id="email" placeholder="Adresse mail">
                <input class="form-control inputLog mr-2" type="password" name="password" id="password" placeholder="Mot de passe">
                <button type="submit" class="button connexionButton">Connexion</button>
            </form>
        </nav>
    </header>

    <div class="title">
    <h1 class="Simelius">Simelius</h1>
    <h2>Ensemble, soyons meilleur</h2>
    </div>
    <a href="#popin1">
        <button class="button inscriptionButton">Rejoindre la communauté</button>
    </a>

    <div class="smart-popin" id="popin1">
        <div class="sp-table">
            <div class="sp-cell">
                <div class="sp-body">
                    <a href="#" class="sp-close">×</a>
                    <div class="centre">
                        <p>
                            Lorem ipsum dolor sit, amet consectetur adipisicing elit. Iusto similique ratione, natus nesciunt eius accusantium dignissimos rerum doloribus recusandae animi architecto ex, vitae debitis odit ducimus officiis. Dolore, velit a?
                        </p>

                        <button class="submitButton nunito text-color"><a href="sign up.html"> Je rejoins la communauté</a></button>

                    </div>
                </div>
            </div>
        </div>
    </div>


    <footer>
        <p class="text-color">Partagez la vôtre et bénéficiez de l'expérience de vos pairs pour acquérir de nouvelles compétences et progresser
            professionnellement.
        </p>
    </footer>

</div>
</body>

</html>