<?php if (!isset($_SESSION['user'])) {
    header('Location: login.php');
} else ?>
<!-- Deux div pour centrer verticalement la popin sur la page -->
<div class="table-popin" xmlns="http://www.w3.org/1999/html">
    <div class="center-popin">

        <header>
            <nav class="navbar navbar-light ">
                <a class="navbar-brand" href="<?=BASE_URL?>/homepage.php">
                    <img class="logoSimelius" src="http://www.efrei.fr/wp-content/uploads/2015/07/logo-Entraide.png" alt="Logo Simelius"><span class="simeliusName merienda">Simelius</span>
                </a>
                <input type="text" class="searchBar form-control nunito" placeholder="Rechercher">
                <div class="dropleft show">
                    <button class="btn dropdown-toggle" type="button" id="dropdownMenuButton" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                        <img src="./images/Pikachu.png" alt="profile-picture" class="nunito profile-picture">
                        <p class="user"><?= $user['firstname'] ; ?></p>
                    </button>
                    <div class="dropdown-menu" aria-labelledby="dropdownMenuLink">
                        <a class="dropdown-item" href="#">Mon profil</a>
                        <a class="dropdown-item" href="#">Mes contributions</a>
                        <a class="dropdown-item" href="#">Mes réponses</a>
                        <a class="dropdown-item" href="#">J'ai jugé pertinent</a>
                        <div class="dropdown-divider"></div>
                        <a class="dropdown-item" href="<?=BASE_URL?>/logout.php">Déconnexion</a>
                    </div>
                </div>
            </nav>
        </header>

        <div class="sidenavleft sidenav nunito">
            <?php foreach ($category as $cat) : ?>
                <div class="sideBarContent">
                    <span class="categoryFilter color-blank <?=$cat['name']?>">
                        <?= $cat['name']; ?>
                    </span>
                </div>
                <script>
                    $('.<?=$cat['name']?>').click(function(){
                        $('.post').hide(1000);
                        $('.category<?=$cat['name']?>').show(1000);

                    });
                </script>
            <?php endforeach;?>
        </div>

        <div class="sidenavright sidenav nunito">
            <div class="sideBarContent">
                <a href="#about" class="color-blank" class="event">Suicide digestif</a>
            </div>
            <div class="sideBarContent">
                <a href="#services" class="color-blank" class="event">Spiritisme collectif</a>
            </div>
            <div class="sideBarContent">
                <a href="#clients" class="color-blank" class="event">Sylvanothérapie</a>
            </div>
            <div class="sideBarContent">
                <a href="#contact" class="color-blank" class="event">Miaou</a>
            </div>
        </div>
        <div class="main">
            
            <form method="post" class="addPost">

                <div class="smart-popin" id="popin1">
                    <div class="sp-table">
                        <div class="sp-cell">
                            <div class="sp-body nunito">
                                <a href="#" class="sp-close">×</a>
                                <input type="text" name="title" placeholder="Mon titre" class="form-control postTitle nunito">
                                <p class="addCategories">On pourra retrouver ma contribution dans les catégories...</p>
                                <?php foreach ($category as $cat) : ?>
                                    <div>
                                        <input name="category[]" type="checkbox" value="<?= $cat['category_id']; ?>" id="c1" />
                                        <label for="c1">
                                            <?= $cat['name']; ?>
                                        </label>
                                    </div>
                                <?php endforeach;?>
                                <button type="submit" class="validButton nunito color-blank">Je valide</button>
                            </div>

                        </div>
                    </div>
            </form>
        </div>
        <?php foreach ($articles as $article) : ?>
            <?php $experience= experience($article['experience'])?>
            <div class="post nunito <?php $categories = explode(',', $article['categories']); ?>
                        <?php foreach ($categories as $category) : ?>
                         category<?= $category ?>
            <?php endforeach ;?>
">
                <h3 class="titrePost merienda">
                    <?= $article['title'] ?>
                </h3>
                <br>
                <div class="categoryPost">
                    <?php if(isset($article['categories'])) : ?>
                        <?php $categories = explode(',', $article['categories']); ?>
                        <?php foreach ($categories as $category) : ?>

                            <button class="categoryBadge"><?= $category ?></button>
                        <?php endforeach ;?>
                    <?php endif; ?>
                </div>
                <div class="poster">
                    <img src="" alt="image" />
                    <?= $article['firstname'] . ' '. $article['lastname']?>,
                    <?php if ($experience[0]<1) : ?>
                        <?= $experience[1]?> jours d'expérience
                    <?php elseif ($experience[0]=1) : ?>
                        <?= $experience[0]?> an et
                        <?= $experience[1]?> jours d'expérience
                    <?php else : ?>
                        <?= $experience[0]?> ans et
                        <?= $experience[1]?> jours d'expérience
                    <?php endif; ?>
                </div>
                <div class="content">
                    <?= $article['content'] ?>
                    <br>
                </div>
                <div class="date nunito">Posté le
                    <?= (new DateTime($article['created_at']))->format('d/m/Y à H:i'); ?>
                </div>

                <form class="commentForm" name="commentForm" action="<?= BASE_URL . DS . 'comment.php' ?>" method="POST">
                    <textarea name="content" onkeyup="auto_grow(this)"  class="writeAnswer nunito form-control commentContent" placeholder="Mon commentaire..."></textarea>
                    <input class="commentButton commentArticleId" type="hidden" name="article_id" id="article_id" value="<?= $article['article_id'] ?>">
                </form>

                <?php  $comments = getComments($db, $article['article_id']); ?>
                <?php $articleRelevance = getArticleRelevance($db, $article['article_id']); ?>
                <?php foreach ($comments as $comment) : ?>
                    <?php $relevance = getRelevance($db, $comment['comment_id']) ;?>
                    <?php $commentRelevance = getCommentRelevance($db, $comment['comment_id']) ; ?>
                    <?php $experience= experience($comment['experience'])?>

                    <div class="showComments showComments<?= $article['article_id']?>" id="showComments<?= $article['article_id']?>">
                        <div class="comments" id="comments<?= $article['article_id']?>">
                            <div class="commentposter nunito">
                                <?= $comment['firstname']?>
                                <?= $comment['lastname']?>,
                                <?php if ($experience[0]<1) : ?>
                                    <?= $experience[1]?> jours d'expérience
                                <?php elseif ($experience[0]=1) : ?>
                                    <?= $experience[0]?> an et
                                    <?= $experience[1]?> jours d'expérience
                                <?php else : ?>
                                    <?= $experience[0]?> ans et
                                    <?= $experience[1]?> jours d'expérience
                                <?php endif; ?>
                            </div>
                            <div class="commentcontent nunito">
                                <?= $comment['content'] ?>
                            </div>
                            <div class="date">
                            <span class="date nunito">Posté le
                                <?= (new DateTime($comment['created_at']))->format('d/m/Y à H:i'); ?>
                            </span>
                                <?php if (empty($relevance) OR (!in_array($_SESSION['user']['user_id'],$relevance ))):?>
                                    <form class="noteComment float-right addRelevance" method="post" action="<?= BASE_URL . DS . 'relevance.php' ?>">
                                <span class="note"><button type="submit" class="relevance">++</button>
                                <i class="fas fa-chart-line"></i> <?= $commentRelevance['count(*)'] ?></span>
                                        <input type="hidden" name="comment_id" value="<?= $comment['comment_id'] ?>">
                                    </form>
                                <?php elseif (in_array($_SESSION['user']['user_id'],$relevance )) : ?>
                                    <form class="noteComment float-right" method="post" action="<?= BASE_URL . DS . 'deleteRelevance.php' ?>">
                                <span class="note "><button type="submit" class="relevance">- -</button>
                                <i class="fas fa-chart-line"></i> <?= $commentRelevance['count(*)'] ?></span>
                                        <input type="hidden" name="comment_id" value="<?= $relevance['comment_id'] ?>">
                                    </form>
                                <?php endif ; ?>
                            </div>
                        </div>
                    </div>
                <?php endforeach; ?>
                <div class="answers">
                    <?php if (!empty($comments)) : ?>
                        <span class="showAnswers" id="showAnswers<?= $article['article_id']?>">
                        Afficher les réponses
                        <span class="pertinence" data-tooltip="Taux de pertinence"><i class="fas fa-chart-line"></i> <?= $articleRelevance['count(*)'] ?></span>
                    </span>
                    <?php else : ?>
                        <span class="showAnswers" id="showAnswers<?= $article['article_id']?>">
                        Actuellement sans réponse
                     </span>
                    <?php endif ;?>
                </div>
            </div>

            <script>
                $('#showAnswers<?= $article['article_id']?>').click(function(){
                    $('.showComments<?= $article['article_id']?>').slideToggle(200)
                });
            </script>
        <?php endforeach ;?>

    </div>
</div>
</body>

<script type="text/javascript">
    $('.commentForm').find('.writeAnswer').keyup(function (e) {
        var e = e || window.event;
        var k = e.keyCode || e.which;
        if (k == 13 && !e.shiftKey) {
            this.form.submit();
        }
    });

    /*   $(document).ready(function(){
           $(".commentForm").submit(function(e) {
               e.preventDefault();
               var answer= $(this).find('.writeAnswer').val();
               var article_id = $(this).find('#article_id').val();
               $.post(
                   '/Simelius/comment.php', {
                       article_id: article_id,
                       content : answer,
                   },
                   function(data){
                       if(data === 'Success'){
                           $("#comments"+article_id).append().html("<p>answer</p>");
                       }
                       else{
                           $("#resultat").html("<p>Erreur...</p>");
                       }
                   },
                   'text'
               );
           });
       }); */

    function auto_grow(element) {
        element.style.height = "5px";
        element.style.height = (element.scrollHeight) + "px";
    };

</script>

</html>
