<?php if (!isset($_SESSION['user'])) {
    header('Location: login.php');
} else ?>
<!-- Deux div pour centrer verticalement la popin sur la page -->
<div class="table-popin" xmlns="http://www.w3.org/1999/html">
    <div class="center-popin">

        <header>
            <nav class="navbar navbar-light ">
                <a class="navbar-brand" href="<?=BASE_URL?>/homepage.php">
                    <img class="logoSimelius" src="http://www.efrei.fr/wp-content/uploads/2015/07/logo-Entraide.png" alt="Logo Simelius"><span class="simeliusName merienda">Simelius</span>
                </a>
                <input type="text" class="searchBar form-control nunito" placeholder="Rechercher">
                <div class="dropleft show">
                    <button class="btn dropdown-toggle" type="button" id="dropdownMenuButton" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                        <img src="<?= $user['profile_picture'] ?>" alt="profile-picture" class="nunito profile-picture">
                        <p class="user"><?= $user['firstname'] . ' ' . $user['lastname']; ?></p>
                    </button>
                    <div class="dropdown-menu" aria-labelledby="dropdownMenuLink">
                        <a class="dropdown-item" href="<?=BASE_URL?>/userProfile.php">Mon profil</a>
                        <a class="dropdown-item" href="<?=BASE_URL?>/myContributions.php">Mes contributions</a>
                        <a class="dropdown-item" href="<?=BASE_URL?>/myComments.php">Mes réponses</a>
                        <a class="dropdown-item" href="<?=BASE_URL?>/myRelevances.php">J'ai jugé pertinent</a>
                        <div class="dropdown-divider"></div>
                        <a class="dropdown-item" href="<?=BASE_URL?>/logout.php">Déconnexion</a>
                    </div>
                </div>
            </nav>
        </header>

        <div class="sidenavleft sidenav nunito">
            <?php foreach ($category as $cat) : ?>
                <div class="sideBarContent">
                    <span class="categoryFilter color-blank <?=$cat['name']?>">
                        <?= $cat['name']; ?>
                    </span>
                </div>
                <script>
                    $('.<?=$cat['name']?>').click(function(){
                        $('.post').hide(1000);
                        $('.category<?=$cat['name']?>').show(1000);

                    });
                </script>
            <?php endforeach;?>
        </div>

        <div class="sidenavright sidenav color-blank nunito">
            <div class="sideBarContent">
                <?= $usersCountByCommunity['count(*)']?> <?= $user['name'] ?>s
            </div>
            <div class="sideBarContent">
                <?= $userArticlesCount['count(*)'] ?> contributions
            </div>
            <div class="sideBarContent">
                <?= $userCommentsCount['count(*)'] ?> réponses
            </div>
            <div class="sideBarContent">
                Taux de pertinence <br> de <?= $relevanceRateByCommunity['COUNT(comment_id)']/3; ?>
            </div>
        </div>
        <div class="main">
            
            <form method="post" class="addPost">

                <div class="smart-popin" id="popin1">
                    <div class="sp-table">
                        <div class="sp-cell">
                            <div class="sp-body nunito">
                                <a href="#" class="sp-close">×</a>
                                <input type="text" name="title" placeholder="Mon titre" class="form-control postTitle nunito">
                                <p class="addCategories">On pourra retrouver ma contribution dans les catégories...</p>
                                <?php foreach ($category as $cat) : ?>
                                    <div>
                                        <input name="category[]" type="checkbox" value="<?= $cat['category_id']; ?>" id="c1" />
                                        <label for="c1">
                                            <?= $cat['name']; ?>
                                        </label>
                                    </div>
                                <?php endforeach;?>
                                <button type="submit" class="validButton nunito color-blank">Je valide</button>
                            </div>

                        </div>
                    </div>
            </form>
        </div>
        <?php include THEME_PATH . DS .'articles.phtml'?>
    </div>
</div>
</body>
</script>
</html>
