<div class="website-content">
    <header>
        <nav class="color-blank nunito">

            <a href="#" class="simeliusName merienda color-blank">
                <img class="logoSimelius" src="http://www.efrei.fr/wp-content/uploads/2015/07/logo-Entraide.png" alt="Logo Simelius">Simelius</a>
        </nav>
    </header>
    <h1>Inscription</h1>
    <form method="POST" postaction="register.php" class="logForm">
        <?php if (!empty($errors)) : ?>
            <?php foreach ($errors as $err) : ?>
                <div class="alert alert-danger"><?= $err; ?></div>
            <?php endforeach; ?>
        <?php endif; ?>
        <input class="form-control" type="text" name="lastname" id="lastname" placeholder="Nom">
        <input class="form-control" type="text" name="firstname" id="firstname" placeholder="Prénom">
        <select class="form-control" name="profession_id">
            <?php foreach ($professionfromdb as $prof) :?>
            <option value="<?= $prof['profession_id']?>"><?= $prof['name']?></option>
            <?php endforeach ?>
        </select>
        <div class="form-group">
            <label for="email" class="sr-only">Email</label>
            <input class="form-control" type="email" name="email" id="email" placeholder="Adresse mail" value="<?= $email; ?>" required autofocus>
            <div id="hasUser" class="invalid-feedback form-text">Cette adresse mail est déjà utilisée.
            </div>
        </div>
        <input class="form-control" type="password" name="password" id="password" placeholder="Mot de passe">
        <input class="form-control" type="password" name="password2" id="password2" placeholder="Vérification du mot de passe">
        <input class="form-control" placeholder="J'ai commencé à exercer..." type="text" onfocus="(this.type='date')" onblur="(this.type='text')" name="birthday" id="date">
        <button type="submit">Je valide</button>
    </form>

    <footer>
        <p class="text-color">Partagez la vôtre et bénéficiez de l'expérience de vos pairs pour acquérir de nouvelles compétences et progresser
            professionnellement.
        </p>
    </footer>

    <script src="<?= BASE_URL ?>/views/<?= THEME ?>/js/register.js"></script>