<body>
<div class="website-content">
    <header>
        <nav class="color-blank nunito">

            <a href="#" class="simeliusName merienda color-blank">
                <img class="logoSimelius" src="http://www.efrei.fr/wp-content/uploads/2015/07/logo-Entraide.png" alt="Logo Simelius">Simelius</a>
        </nav>
    </header>
    <h1>Inscription</h1>
    <form method postaction="register.php" class="logForm">

        <input type="text" name="lastname" id="lastname" placeholder="Nom">
        <input type="text" name="fisrtname" id="firstname" placeholder="Prénom">
        <select name="profession">
            <option value="Architecte">Architecte</option>
            <option value="Développeur">Développeur</option>
            <option value="Pompier">Pompier</option>
        </select>
        <input type="mail" name="email" id="email" placeholder="Adresse mail">
        <input type="password" name="password" id="password" placeholder="Mot de passe">
        <input type="password" name="password2" id="password2" placeholder="Vérification du mot de passe">
        <input type="date" placeholder="Date de naissance" value="Date de naissance">
        <button type="submit button">Je valide</button>
    </form>

    <footer>
        <p class="text-color">Partagez la vôtre et bénéficiez de l'expérience de vos pairs pour acquérir de nouvelles compétences et progresser
            professionnellement.
        </p>
    </footer>