<body>
<div class="website-content">
    <header>
        <nav class="color-blank nunito">

            <a href="#" class="simeliusName merienda color-blank">
                <img class="logoSimelius" src="http://www.efrei.fr/wp-content/uploads/2015/07/logo-Entraide.png" alt="Logo Simelius">Simelius</a>
        </nav>
    </header>
    <h1>Inscription</h1>
    <form method="POST" postaction="register.php" class="logForm">
        <?php if (!empty($errors)) : ?>
            <?php foreach ($errors as $err) : ?>
                <div class="alert alert-danger"><?= $err; ?></div>
            <?php endforeach; ?>
        <?php endif; ?>
        <input type="text" name="lastname" id="lastname" placeholder="Nom">
        <input type="text" name="firstname" id="firstname" placeholder="Prénom">
        <select name="profession_id">
            <?php foreach ($professionfromdb as $prof) :?>
            <option value="<?= $prof['profession_id']?>"><?= $prof['name']?></option>
            <?php endforeach ?>
        </select>
        <input type="email" name="email" id="email" placeholder="Adresse mail">
        <input type="password" name="password" id="password" placeholder="Mot de passe">
        <input type="password" name="password2" id="password2" placeholder="Vérification du mot de passe">
        <input type="date" placeholder="Date de naissance" value="Date de naissance">
        <button type="submit">Je valide</button>
    </form>

    <footer>
        <p class="text-color">Partagez la vôtre et bénéficiez de l'expérience de vos pairs pour acquérir de nouvelles compétences et progresser
            professionnellement.
        </p>
    </footer>