<?php if (!isset($_SESSION['user'])) {
    header('Location: login.php');
} else ?>
        <header>
            <nav class="navbar navbar-light ">
                <a class="navbar-brand" href="<?=BASE_URL?>/homepage.php">
                    <img class="logoSimelius" src="http://www.efrei.fr/wp-content/uploads/2015/07/logo-Entraide.png" alt="Logo Simelius"><span class="simeliusName merienda">Simelius</span>
                </a>
                <input type="text" class="searchBar form-control nunito" placeholder="Rechercher">
                <div class="dropleft show">
                    <button class="btn dropdown-toggle" type="button" id="dropdownMenuButton" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                        <img src="<?=$user['profile_picture']?>" alt="profile-picture" class="nunito profile-picture">
                        <p class="user"><?= $user['firstname'] ; ?></p>
                    </button>
                    <div class="dropdown-menu" aria-labelledby="dropdownMenuLink">
                        <a class="dropdown-item" href="<?=BASE_URL?>/userProfile.php">Mon profil</a>
                        <a class="dropdown-item" href="<?=BASE_URL?>/myContributions.php">Mes contributions</a>
                        <a class="dropdown-item" href="<?=BASE_URL?>/myComments.php">Mes réponses</a>
                        <a class="dropdown-item" href="<?=BASE_URL?>/myRelevances.php">J'ai jugé pertinent</a>
                        <div class="dropdown-divider"></div>
                        <a class="dropdown-item" href="<?=BASE_URL?>/logout.php">Déconnexion</a>
                    </div>
                </div>
            </nav>
        </header>

        <div class="sidenavleft sidenav nunito">
            <?php foreach ($category as $cat) : ?>
                <div class="sideBarContent">
                    <span class="categoryFilter color-blank <?=$cat['name']?>">
                        <?= $cat['name']; ?>
                    </span>
                </div>
                <script>
                    $('.<?=$cat['name']?>').click(function(){
                        $('.post').hide(1000);
                        $('.category<?=$cat['name']?>').show(1000);

                    });
                </script>
            <?php endforeach;?>
        </div>

        <div class="sidenavright sidenav nunito">
            <div class="sideBarContent">
                <a href="#about" class="color-blank" class="event">Suicide digestif</a>
            </div>
            <div class="sideBarContent">
                <a href="#services" class="color-blank" class="event">Spiritisme collectif</a>
            </div>
            <div class="sideBarContent">
                <a href="#clients" class="color-blank" class="event">Sylvanothérapie</a>
            </div>
            <div class="sideBarContent">
                <a href="#contact" class="color-blank" class="event">Miaou</a>
            </div>
        </div>

        <img src="<?= $user['profile_picture']?>" alt="Photo de profil" width="400" class="profile-picture-userProfile push-3 mt6">
<div class="userInformations">
    <div class="name-userProfile mt-3">
    <?= $user['firstname'] . ' ' . $user['lastname']?>
    </div>
</div>

</body>

<script src="<?= BASE_URL ?>/views/<?= THEME ?>/js/articles.js">

    </html>