<?php if (!isset($_SESSION['user'])) {
    header('Location: login.php');
} else ?>
        <header>
            <nav class="navbar navbar-light ">
                <a class="navbar-brand" href="<?=BASE_URL?>/homepage.php">
                    <img class="logoSimelius" src="http://www.efrei.fr/wp-content/uploads/2015/07/logo-Entraide.png" alt="Logo Simelius"><span class="simeliusName merienda">Simelius</span>
                </a>
                <input type="text" class="searchBar form-control nunito" placeholder="Rechercher">
                <div class="dropleft show">
                    <button class="btn dropdown-toggle" type="button" id="dropdownMenuButton" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                        <img src="<?=$user['profile_picture']?>" alt="profile-picture" class="nunito profile-picture">
                        <p class="user"><?= $user['firstname'] . ' ' . $user['lastname']; ?></p>
                    </button>
                    <div class="dropdown-menu" aria-labelledby="dropdownMenuLink">
                        <a class="dropdown-item" href="<?=BASE_URL?>/userProfile.php">Mon profil</a>
                        <a class="dropdown-item" href="<?=BASE_URL?>/myContributions.php">Mes contributions</a>
                        <a class="dropdown-item" href="<?=BASE_URL?>/myComments.php">Mes réponses</a>
                        <a class="dropdown-item" href="<?=BASE_URL?>/myRelevances.php">J'ai jugé pertinent</a>
                        <div class="dropdown-divider"></div>
                        <a class="dropdown-item" href="<?=BASE_URL?>/logout.php">Déconnexion</a>
                    </div>
                </div>
            </nav>
        </header>

<div class="sidenavleft sidenav color-blank nunito">
    <div class="sideBarContent">
        <?php if (($userArticlesCount['count(*)'] + $userCommentsCount['count(*)'] + $userRelevanceRate['COUNT(comment_id)']) <50) : ?>
            Jeune membre
        <?php elseif (($userArticlesCount['count(*)'] + $userCommentsCount['count(*)'] + $userRelevanceRate['COUNT(comment_id)']) < 100) :?>
            Membre actif
        <?php elseif (($userArticlesCount['count(*)'] + $userCommentsCount['count(*)'] + $userRelevanceRate['COUNT(comment_id)']) < 150) :?>
            Membre expérimenté
        <?php elseif (($userArticlesCount['count(*)'] + $userCommentsCount['count(*)'] + $userRelevanceRate['COUNT(comment_id)']) < 200) :?>
            Membre émérite
        <?php endif;?>
    </div>
    <div class="sideBarContent">
        <?= $userArticlesCount['count(*)'] ?> contributions
    </div>
    <div class="sideBarContent">
        <?= $userCommentsCount['count(*)'] ?> réponses
    </div>
    <div class="sideBarContent">
        Taux de pertinence <br> de <?= $userRelevanceRate['COUNT(comment_id)']; ?>
    </div>
</div>

        <div class="sidenavright sidenav nunito">
            <div class="sideBarContent">
                <a href="#about" class="color-blank" class="event">Suicide digestif</a>
            </div>
            <div class="sideBarContent">
                <a href="#services" class="color-blank" class="event">Spiritisme collectif</a>
            </div>
            <div class="sideBarContent">
                <a href="#clients" class="color-blank" class="event">Sylvanothérapie</a>
            </div>
            <div class="sideBarContent">
                <a href="#contact" class="color-blank" class="event">Miaou</a>
            </div>
        </div>

<div class="userInformations">
        <img src="<?= $user['profile_picture']?>" alt="Photo de profil" width="400" class="profile-picture-userProfile nunito push-3 mt6">
    <div class="name-userProfile mt-3">
    <?= $user['firstname'] . ' ' . $user['lastname']?>
    </div>
    <div class="society-userProfile mt-3">
        <?= $user['society'] ?>
    </div>
    <div class="mt-3">
    <?php if ($experience[0]<1) : ?>
                            <?= $experience[1]?> jours d'expérience
                        <?php elseif ($experience[0]=1) : ?>
                            <?= $experience[0]?> an et
                            <?= $experience[1]?> jours d'expérience
                        <?php else : ?>
                            <?= $experience[0]?> ans et
                            <?= $experience[1]?> jours d'expérience
                        <?php endif; ?>
    </div>
    <div class="mt-3">
        <?=$user['email']?>
    </div>
    <button class="updateUserInformationsButton nunito color-blank mt-3">Modifier mes informations</button>
</div>
<div class="updateUserInformationsForm">
<form method="POST" action="<?=BASE_URL . DS . 'updateUser.php' ?>"  enctype="multipart/form-data">
    <?php if (!empty($errors)) : ?>
        <?php foreach ($errors as $err) : ?>
            <div class="alert alert-danger"><?= $err; ?></div>
        <?php endforeach; ?>
    <?php endif; ?>
    <div class="form-group">
        <input class="form-control mt-2" type="text" name="lastname" id="lastname" value="<?=$user['lastname']?>">
        <input class="form-control mt-2" type="text" name="firstname" id="firstname" value="<?=$user['firstname'] ?>">
        <label for="email" class="sr-only">Email</label>
        <input class="form-control mt-2" type="email" name="email" id="registerMail" value="<?= $user['email']; ?>" required autofocus>
        <div id="hasUser" class="invalid-feedback form-text">Cette adresse mail est déjà utilisée.
        </div>
        <input class="form-control mt-2" type="password" name="password" id="password" placeholder="Nouveau mot de passe">
        <input class="form-control mt-2" type="password" name="password2" id="password2" placeholder="Vérification du mot de passe">
        <input class="form-control mt-2" type="text" name="society" placeholder="Société" value="<?=$user['society'] ?>">
        <input class="form-control mt-2" placeholder="J'ai commencé à exercer..." type="text" onfocus="(this.type='date')" onblur="(this.type='text')" name="birthday" id="date" value="<?= $user['experience']?>">
        <input class="form-control mt-2" type="file" id="monfichier" name="profile_picture" value="<?= $user['profile_picture']?>">

        <button class="updateUserInformationsValidButton nunito color-blank mt-4 mb-5"> Je valide</button>
    </div>
</div>
</form>

</body>

<script src="<?= BASE_URL ?>/views/<?= THEME ?>/js/userProfile.js">
    </script>
    </html>